import { Patient } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: '김서연',
    age: 34,
    gender: '여성',
    skinType: 'III',
    phoneNumber: '010-1234-5678',
    registrationDate: '2024-03-15',
    lastVisit: '2025-12-17',
    primaryConcerns: ['기미', '잔주름', '모공'],
    allergies: [],
    medicalHistory: [],
    visitCount: 8,
    status: '상담 중',
  },
  {
    id: 'P002',
    name: '이준호',
    age: 42,
    gender: '남성',
    skinType: 'IV',
    phoneNumber: '010-2345-6789',
    registrationDate: '2024-06-20',
    lastVisit: '2025-12-16',
    primaryConcerns: ['색소침착', '여드름 흉터'],
    allergies: ['리도카인'],
    medicalHistory: ['고혈압'],
    visitCount: 5,
    status: '분석 대기',
  },
  {
    id: 'P003',
    name: '박민지',
    age: 28,
    gender: '여성',
    skinType: 'II',
    phoneNumber: '010-3456-7890',
    registrationDate: '2024-09-10',
    lastVisit: '2025-12-17',
    primaryConcerns: ['홍조', '민감성', '피부결'],
    allergies: [],
    medicalHistory: [],
    visitCount: 3,
    status: '분석 대기',
  },
  {
    id: 'P004',
    name: '최영수',
    age: 51,
    gender: '남성',
    skinType: 'III',
    phoneNumber: '010-4567-8901',
    registrationDate: '2023-11-05',
    lastVisit: '2025-12-15',
    primaryConcerns: ['주름', '탄력저하', '처짐'],
    allergies: [],
    medicalHistory: ['당뇨'],
    visitCount: 12,
    status: '완료',
  },
  {
    id: 'P005',
    name: '정수빈',
    age: 25,
    gender: '여성',
    skinType: 'II',
    phoneNumber: '010-5678-9012',
    registrationDate: '2025-01-15',
    lastVisit: '2025-12-17',
    primaryConcerns: ['여드름', '모공', '피지'],
    allergies: [],
    medicalHistory: [],
    visitCount: 6,
    status: '상담 중',
  },
  {
    id: 'P006',
    name: '한지민',
    age: 38,
    gender: '여성',
    skinType: 'III',
    phoneNumber: '010-6789-0123',
    registrationDate: '2024-04-22',
    lastVisit: '2025-12-14',
    primaryConcerns: ['기미', '주근깨', '피부톤'],
    allergies: [],
    medicalHistory: [],
    visitCount: 10,
    status: '완료',
  },
  {
    id: 'P007',
    name: '오민석',
    age: 45,
    gender: '남성',
    skinType: 'IV',
    phoneNumber: '010-7890-1234',
    registrationDate: '2024-02-18',
    lastVisit: '2025-12-16',
    primaryConcerns: ['주름', '탄력저하', '모공'],
    allergies: ['아스피린'],
    medicalHistory: [],
    visitCount: 7,
    status: '예약됨',
  },
  {
    id: 'P008',
    name: '강예원',
    age: 31,
    gender: '여성',
    skinType: 'II',
    phoneNumber: '010-8901-2345',
    registrationDate: '2024-08-30',
    lastVisit: '2025-12-17',
    primaryConcerns: ['다크서클', '피부결', '수분부족'],
    allergies: [],
    medicalHistory: [],
    visitCount: 4,
    status: '분석 대기',
  },
  {
    id: 'P009',
    name: '임현우',
    age: 36,
    gender: '남성',
    skinType: 'III',
    phoneNumber: '010-9012-3456',
    registrationDate: '2024-05-12',
    lastVisit: '2025-12-13',
    primaryConcerns: ['색소침착', '여드름 흉터', '모공'],
    allergies: [],
    medicalHistory: [],
    visitCount: 9,
    status: '완료',
  },
  {
    id: 'P010',
    name: '송다은',
    age: 29,
    gender: '여성',
    skinType: 'I',
    phoneNumber: '010-0123-4567',
    registrationDate: '2025-02-08',
    lastVisit: '2025-12-17',
    primaryConcerns: ['홍조', '민감성', '혈관확장'],
    allergies: ['페니실린'],
    medicalHistory: ['아토피'],
    visitCount: 2,
    status: '상담 중',
  },
  {
    id: 'P011',
    name: '유재현',
    age: 48,
    gender: '남성',
    skinType: 'IV',
    phoneNumber: '010-1111-2222',
    registrationDate: '2023-09-25',
    lastVisit: '2025-12-12',
    primaryConcerns: ['주름', '처짐', '색소침착'],
    allergies: [],
    medicalHistory: ['고지혈증'],
    visitCount: 15,
    status: '예약됨',
  },
  {
    id: 'P012',
    name: '백서윤',
    age: 33,
    gender: '여성',
    skinType: 'III',
    phoneNumber: '010-2222-3333',
    registrationDate: '2024-07-19',
    lastVisit: '2025-12-16',
    primaryConcerns: ['기미', '잔주름', '탄력'],
    allergies: [],
    medicalHistory: [],
    visitCount: 6,
    status: '분석 대기',
  },
  {
    id: 'P013',
    name: '신동욱',
    age: 40,
    gender: '남성',
    skinType: 'III',
    phoneNumber: '010-3333-4444',
    registrationDate: '2024-01-30',
    lastVisit: '2025-12-15',
    primaryConcerns: ['피지', '모공', '여드름'],
    allergies: [],
    medicalHistory: [],
    visitCount: 11,
    status: '완료',
  },
  {
    id: 'P014',
    name: '문지영',
    age: 27,
    gender: '여성',
    skinType: 'II',
    phoneNumber: '010-4444-5555',
    registrationDate: '2025-03-05',
    lastVisit: '2025-12-17',
    primaryConcerns: ['피부결', '수분', '광채'],
    allergies: [],
    medicalHistory: [],
    visitCount: 3,
    status: '상담 중',
  },
  {
    id: 'P015',
    name: '권태훈',
    age: 55,
    gender: '남성',
    skinType: 'V',
    phoneNumber: '010-5555-6666',
    registrationDate: '2023-06-14',
    lastVisit: '2025-12-11',
    primaryConcerns: ['주름', '처짐', '탄력저하'],
    allergies: [],
    medicalHistory: ['당뇨', '고혈압'],
    visitCount: 20,
    status: '완료',
  },
];

export const getPatientById = (id: string): Patient | undefined => {
  return mockPatients.find(p => p.id === id);
};

export const getPatientsByStatus = (status: Patient['status']): Patient[] => {
  return mockPatients.filter(p => p.status === status);
};

export const getTodayPatients = (): Patient[] => {
  const today = new Date().toISOString().split('T')[0];
  return mockPatients.filter(p => p.lastVisit === today || p.status === '분석 대기' || p.status === '상담 중');
};
