import { Recommendation, SimilarCase, DashboardStats, RecentActivity } from '../types';

export const mockRecommendations: Recommendation[] = [
  {
    id: 'R001',
    analysisId: 'A001',
    patientId: 'P001',
    generatedAt: '2025-12-17T09:35:00',
    confidence: 0.92,
    primaryTreatment: {
      treatmentId: 'T001',
      nameKo: '피코토닝',
      nameEn: 'Pico Toning',
      sessions: 8,
      interval: '2주',
      intensity: '중강도',
      rationale: '양 볼의 색소침착 수치가 높아 피코토닝이 가장 효과적입니다. 기미와 색소침착에 대한 92%의 개선 예상률을 보이며, 피부 타입 III에 안전합니다.',
      confidence: 0.92,
    },
    secondaryTreatments: [
      {
        treatmentId: 'T003',
        nameKo: '리쥬란',
        nameEn: 'Rejuran Healer',
        sessions: 4,
        interval: '3주',
        intensity: '표준',
        rationale: '잔주름과 피부결 개선을 위해 피코토닝과 병행하면 시너지 효과가 있습니다.',
        confidence: 0.78,
      },
      {
        treatmentId: 'T019',
        nameKo: '트라넥삼산 이온토',
        nameEn: 'Tranexamic Acid Ionto',
        sessions: 10,
        interval: '1주',
        intensity: '저강도',
        rationale: '레이저 시술 사이에 색소 생성 억제를 위한 보조 치료로 권장됩니다.',
        confidence: 0.72,
      },
    ],
    contraindications: [],
    expectedOutcome: '8주 후 색소침착 60-70% 개선, 피부 톤 균일화, 잔주름 30% 감소 예상',
    similarCases: [
      {
        caseId: 'SC001',
        patientName: '이**',
        similarity: 0.89,
        diagnosis: '양볼 기미, 잔주름',
        treatment: 'Pico Toning 10회 + Rejuran 4회',
        outcome: '색소 75% 개선',
        satisfaction: 5,
      },
      {
        caseId: 'SC002',
        patientName: '박**',
        similarity: 0.85,
        diagnosis: '광대 기미, 피부톤 불균일',
        treatment: 'Pico Toning 8회',
        outcome: '색소 65% 개선',
        satisfaction: 4,
      },
      {
        caseId: 'SC003',
        patientName: '최**',
        similarity: 0.82,
        diagnosis: '기미, 색소침착',
        treatment: 'Pico Toning 6회 + 이온토 15회',
        outcome: '색소 70% 개선',
        satisfaction: 5,
      },
    ],
    aiReasoning: '환자의 피부 분석 결과, 양 볼의 색소침착 수치가 80점 이상으로 높게 측정되었습니다. 유사한 패턴을 보인 과거 환자 312명의 데이터를 분석한 결과, 피코토닝이 가장 높은 개선율(평균 68%)을 보였습니다. 환자의 피부 타입(III)과 나이(34세)를 고려할 때, 중강도의 피코토닝 8회가 최적의 프로토콜로 판단됩니다.',
  },
  {
    id: 'R002',
    analysisId: 'A002',
    patientId: 'P002',
    generatedAt: '2025-12-16T14:20:00',
    confidence: 0.88,
    primaryTreatment: {
      treatmentId: 'T009',
      nameKo: '프락셀',
      nameEn: 'Fraxel',
      sessions: 4,
      interval: '4주',
      intensity: '중강도',
      rationale: '여드름 흉터와 모공 문제에 프랙셔널 레이저가 가장 효과적입니다. 피부 재생을 통한 흉터 개선이 기대됩니다.',
      confidence: 0.88,
    },
    secondaryTreatments: [
      {
        treatmentId: 'T010',
        nameKo: '스킨보톡스',
        nameEn: 'Skin Botox',
        sessions: 2,
        interval: '2개월',
        intensity: '표준',
        rationale: '피지 분비 조절과 모공 축소를 위해 프락셀 치료 후 병행을 권장합니다.',
        confidence: 0.75,
      },
    ],
    contraindications: ['리도카인 알레르기 - 시술 전 대체 마취제 준비 필요'],
    expectedOutcome: '16주 후 여드름 흉터 50-60% 개선, 모공 40% 축소 예상',
    similarCases: [
      {
        caseId: 'SC004',
        patientName: '김**',
        similarity: 0.91,
        diagnosis: '여드름 흉터, 넓은 모공',
        treatment: 'Fraxel 5회 + Skin Botox 2회',
        outcome: '흉터 60% 개선',
        satisfaction: 4,
      },
    ],
    aiReasoning: '환자의 주요 문제점인 여드름 흉터와 넓은 모공에 대해, 프랙셔널 레이저(프락셀)가 최적의 1차 치료로 판단됩니다. 단, 환자의 리도카인 알레르기를 고려하여 대체 마취제 사용이 필요합니다.',
  },
  {
    id: 'R003',
    analysisId: 'A003',
    patientId: 'P003',
    generatedAt: '2025-12-17T10:50:00',
    confidence: 0.85,
    primaryTreatment: {
      treatmentId: 'T008',
      nameKo: '제네시스',
      nameEn: 'Genesis',
      sessions: 10,
      interval: '2주',
      intensity: '저강도',
      rationale: '민감성 피부와 홍조에 적합한 저자극 레이저입니다. 혈관 개선과 피부 진정 효과가 있습니다.',
      confidence: 0.85,
    },
    secondaryTreatments: [
      {
        treatmentId: 'T011',
        nameKo: '물광주사',
        nameEn: 'Hydra Boost',
        sessions: 5,
        interval: '2주',
        intensity: '저강도',
        rationale: '수분 공급을 통한 피부 장벽 강화가 홍조 개선에 도움이 됩니다.',
        confidence: 0.70,
      },
    ],
    contraindications: [],
    expectedOutcome: '20주 후 홍조 50-60% 개선, 피부 장벽 강화, 민감도 감소 예상',
    similarCases: [
      {
        caseId: 'SC005',
        patientName: '정**',
        similarity: 0.87,
        diagnosis: '홍조, 민감성 피부',
        treatment: 'Genesis 12회 + Hydra 6회',
        outcome: '홍조 55% 개선',
        satisfaction: 4,
      },
    ],
    aiReasoning: '환자의 양 볼 홍조 수치가 80점 이상으로 심한 편이며, 민감성 피부로 자극적인 시술은 피해야 합니다. 제네시스는 비접촉식 레이저로 민감성 피부에 안전하며, 홍조 개선에 효과적입니다.',
  },
  {
    id: 'R004',
    analysisId: 'A004',
    patientId: 'P004',
    generatedAt: '2025-12-15T11:05:00',
    confidence: 0.90,
    primaryTreatment: {
      treatmentId: 'T002',
      nameKo: '울쎄라',
      nameEn: 'Ultherapy',
      sessions: 1,
      interval: '1년',
      intensity: '고강도',
      rationale: '심한 피부 처짐과 탄력 저하에 HIFU 리프팅이 가장 효과적입니다. 즉각적인 리프팅과 장기적인 콜라겐 생성 효과가 있습니다.',
      confidence: 0.90,
    },
    secondaryTreatments: [
      {
        treatmentId: 'T014',
        nameKo: '스컬트라',
        nameEn: 'Sculptra',
        sessions: 3,
        interval: '4주',
        intensity: '표준',
        rationale: '콜라겐 자극을 통한 자연스러운 볼륨 개선으로 울쎄라 효과를 극대화합니다.',
        confidence: 0.82,
      },
      {
        treatmentId: 'T005',
        nameKo: '보톡스',
        nameEn: 'Botox',
        sessions: 1,
        interval: '4개월',
        intensity: '표준',
        rationale: '이마와 미간의 표정 주름 개선을 위해 보톡스를 권장합니다.',
        confidence: 0.88,
      },
    ],
    contraindications: ['당뇨 환자 - 시술 후 회복에 주의 필요'],
    expectedOutcome: '3개월 후 리프팅 효과 최대, 주름 40-50% 개선, 탄력 50% 향상 예상',
    similarCases: [
      {
        caseId: 'SC006',
        patientName: '오**',
        similarity: 0.88,
        diagnosis: '피부 처짐, 탄력 저하, 주름',
        treatment: 'Ultherapy + Sculptra 3회',
        outcome: '리프팅 효과 우수',
        satisfaction: 5,
      },
    ],
    aiReasoning: '51세 남성 환자로 피부 노화 징후가 뚜렷합니다. 탄력 점수가 25-35점으로 매우 낮고, 주름 점수가 70점 이상으로 높습니다. HIFU(울쎄라)를 통한 리프팅이 가장 효과적이며, 스컬트라를 통한 콜라겐 자극이 장기적인 개선에 도움이 됩니다.',
  },
  {
    id: 'R005',
    analysisId: 'A005',
    patientId: 'P005',
    generatedAt: '2025-12-17T08:35:00',
    confidence: 0.87,
    primaryTreatment: {
      treatmentId: 'T010',
      nameKo: '스킨보톡스',
      nameEn: 'Skin Botox',
      sessions: 2,
      interval: '2개월',
      intensity: '표준',
      rationale: '과도한 피지 분비와 넓은 모공에 스킨보톡스가 효과적입니다. 피지선 활동 억제로 여드름 예방에도 도움이 됩니다.',
      confidence: 0.87,
    },
    secondaryTreatments: [
      {
        treatmentId: 'T015',
        nameKo: '아쿠아필',
        nameEn: 'Aqua Peel',
        sessions: 4,
        interval: '2주',
        intensity: '표준',
        rationale: '정기적인 딥클렌징으로 모공 관리와 블랙헤드 제거에 효과적입니다.',
        confidence: 0.80,
      },
    ],
    contraindications: [],
    expectedOutcome: '4개월 후 피지 분비 60% 감소, 모공 40% 축소, 여드름 빈도 감소 예상',
    similarCases: [
      {
        caseId: 'SC007',
        patientName: '한**',
        similarity: 0.86,
        diagnosis: '과다 피지, 넓은 모공, 여드름',
        treatment: 'Skin Botox + Aqua Peel 6회',
        outcome: '피지 55% 감소',
        satisfaction: 4,
      },
    ],
    aiReasoning: '25세 여성 환자로 피지와 모공 점수가 80점 이상으로 높습니다. 스킨보톡스를 통한 피지 조절이 근본적인 해결책이며, 아쿠아필을 통한 정기적인 관리가 효과를 유지하는 데 도움이 됩니다.',
  },
];

export const mockDashboardStats: DashboardStats = {
  todayPatients: 12,
  pendingAnalysis: 4,
  completedConsultations: 7,
  acceptanceRate: 0.89,
  averageSatisfaction: 4.6,
};

export const mockRecentActivity: RecentActivity[] = [
  {
    id: 'RA001',
    type: 'analysis',
    patientName: '김서연',
    description: '피부 분석 완료',
    timestamp: '2025-12-17T09:30:00',
  },
  {
    id: 'RA002',
    type: 'recommendation',
    patientName: '김서연',
    description: 'AI 추천 생성: Pico Toning',
    timestamp: '2025-12-17T09:35:00',
  },
  {
    id: 'RA003',
    type: 'consultation',
    patientName: '정수빈',
    description: '상담 진행 중',
    timestamp: '2025-12-17T10:00:00',
  },
  {
    id: 'RA004',
    type: 'analysis',
    patientName: '박민지',
    description: '피부 분석 완료',
    timestamp: '2025-12-17T10:45:00',
  },
  {
    id: 'RA005',
    type: 'recommendation',
    patientName: '박민지',
    description: 'AI 추천 생성: Genesis',
    timestamp: '2025-12-17T10:50:00',
  },
  {
    id: 'RA006',
    type: 'treatment',
    patientName: '최영수',
    description: 'Ultherapy 시술 예약 완료',
    timestamp: '2025-12-17T11:15:00',
  },
  {
    id: 'RA007',
    type: 'consultation',
    patientName: '송다은',
    description: '상담 시작',
    timestamp: '2025-12-17T14:30:00',
  },
  {
    id: 'RA008',
    type: 'analysis',
    patientName: '강예원',
    description: '분석 대기 중',
    timestamp: '2025-12-17T13:20:00',
  },
];

export const getRecommendationByPatientId = (patientId: string): Recommendation | undefined => {
  return mockRecommendations.find(r => r.patientId === patientId);
};

export const getRecommendationByAnalysisId = (analysisId: string): Recommendation | undefined => {
  return mockRecommendations.find(r => r.analysisId === analysisId);
};
