import { Treatment } from '../types';

export const mockTreatments: Treatment[] = [
  {
    id: 'T001',
    nameKo: '피코토닝',
    nameEn: 'Pico Toning',
    category: 'laser',
    description: '피코초 레이저를 이용한 색소 치료로, 기미, 잡티, 피부톤 개선에 효과적입니다.',
    indications: ['기미', '색소침착', '피부톤 개선', '잡티', '주근깨'],
    contraindications: ['임신', '수유 중', '광과민성 약물 복용', '켈로이드 체질'],
    typicalSessions: { min: 5, max: 10 },
    intervalDays: { min: 14, max: 21 },
    downtime: '없음 ~ 1일',
    priceRange: { min: 150000, max: 300000 },
    effectiveness: { '기미': 0.85, '색소침착': 0.9, '피부톤': 0.8, '잡티': 0.85 },
  },
  {
    id: 'T002',
    nameKo: '울쎄라',
    nameEn: 'Ultherapy',
    category: 'device',
    description: '고강도 집속 초음파(HIFU)를 이용한 비침습적 리프팅 시술입니다.',
    indications: ['피부처짐', '리프팅', '탄력개선', '주름', '턱선 정리'],
    contraindications: ['임신', '금속 임플란트', '피부 감염', '출혈성 질환'],
    typicalSessions: { min: 1, max: 2 },
    intervalDays: { min: 180, max: 365 },
    downtime: '1-3일 (붓기)',
    priceRange: { min: 1500000, max: 3000000 },
    effectiveness: { '처짐': 0.9, '탄력': 0.85, '주름': 0.75 },
  },
  {
    id: 'T003',
    nameKo: '리쥬란',
    nameEn: 'Rejuran Healer',
    category: 'injectable',
    description: 'PDRN 성분의 피부 재생 주사로, 피부 탄력과 재생을 촉진합니다.',
    indications: ['피부재생', '잔주름', '탄력', '모공', '피부결 개선'],
    contraindications: ['어류 알레르기', '임신', '수유 중', '켈로이드 체질'],
    typicalSessions: { min: 3, max: 5 },
    intervalDays: { min: 14, max: 28 },
    downtime: '1-2일 (멍)',
    priceRange: { min: 200000, max: 400000 },
    effectiveness: { '탄력': 0.85, '잔주름': 0.8, '피부결': 0.85, '모공': 0.7 },
  },
  {
    id: 'T004',
    nameKo: '슈링크 유니버스',
    nameEn: 'Shurink Universe',
    category: 'device',
    description: '360도 회전 방식의 HIFU 리프팅으로, 균일하고 정밀한 시술이 가능합니다.',
    indications: ['리프팅', '탄력개선', '피부처짐', '이중턱', '팔자주름'],
    contraindications: ['임신', '금속 임플란트', '피부 감염'],
    typicalSessions: { min: 1, max: 3 },
    intervalDays: { min: 90, max: 180 },
    downtime: '없음 ~ 1일',
    priceRange: { min: 500000, max: 1200000 },
    effectiveness: { '리프팅': 0.88, '탄력': 0.85, '처짐': 0.85 },
  },
  {
    id: 'T005',
    nameKo: '보톡스',
    nameEn: 'Botox',
    category: 'injectable',
    description: '보툴리눔 톡신을 이용한 주름 개선 및 윤곽 시술입니다.',
    indications: ['표정주름', '이마주름', '미간주름', '눈가주름', '사각턱'],
    contraindications: ['임신', '수유 중', '근무력증', '보톡스 알레르기'],
    typicalSessions: { min: 1, max: 1 },
    intervalDays: { min: 90, max: 180 },
    downtime: '없음',
    priceRange: { min: 100000, max: 500000 },
    effectiveness: { '표정주름': 0.95, '이마주름': 0.9, '미간주름': 0.92 },
  },
  {
    id: 'T006',
    nameKo: '필러',
    nameEn: 'Filler',
    category: 'injectable',
    description: '히알루론산 필러를 이용한 볼륨 및 주름 개선 시술입니다.',
    indications: ['팔자주름', '볼륨부족', '입술', '턱끝', '다크서클'],
    contraindications: ['임신', '수유 중', '히알루론산 알레르기', '피부 감염'],
    typicalSessions: { min: 1, max: 1 },
    intervalDays: { min: 180, max: 365 },
    downtime: '1-3일 (붓기, 멍)',
    priceRange: { min: 300000, max: 800000 },
    effectiveness: { '팔자주름': 0.9, '볼륨': 0.95, '다크서클': 0.7 },
  },
  {
    id: 'T007',
    nameKo: '인모드',
    nameEn: 'InMode',
    category: 'device',
    description: 'RF 에너지를 이용한 피부 타이트닝 및 지방 감소 시술입니다.',
    indications: ['피부타이트닝', '셀룰라이트', '탄력개선', '지방감소'],
    contraindications: ['임신', '심장박동기', '금속 임플란트'],
    typicalSessions: { min: 3, max: 6 },
    intervalDays: { min: 14, max: 28 },
    downtime: '없음 ~ 1일',
    priceRange: { min: 200000, max: 500000 },
    effectiveness: { '타이트닝': 0.85, '탄력': 0.8, '셀룰라이트': 0.75 },
  },
  {
    id: 'T008',
    nameKo: '제네시스',
    nameEn: 'Genesis',
    category: 'laser',
    description: '1064nm Nd:YAG 레이저를 이용한 피부 톤 및 홍조 개선 시술입니다.',
    indications: ['홍조', '모세혈관확장', '피부결', '모공', '피부톤'],
    contraindications: ['광과민성', '피부 감염', '임신'],
    typicalSessions: { min: 5, max: 10 },
    intervalDays: { min: 14, max: 21 },
    downtime: '없음',
    priceRange: { min: 100000, max: 200000 },
    effectiveness: { '홍조': 0.85, '혈관확장': 0.8, '피부결': 0.75, '모공': 0.7 },
  },
  {
    id: 'T009',
    nameKo: '프락셀',
    nameEn: 'Fraxel',
    category: 'laser',
    description: '프랙셔널 레이저를 이용한 피부 재생 및 흉터 개선 시술입니다.',
    indications: ['여드름흉터', '모공', '잔주름', '피부결', '색소침착'],
    contraindications: ['켈로이드 체질', '광과민성', '임신', '활동성 여드름'],
    typicalSessions: { min: 3, max: 5 },
    intervalDays: { min: 30, max: 60 },
    downtime: '3-7일',
    priceRange: { min: 300000, max: 600000 },
    effectiveness: { '여드름흉터': 0.85, '모공': 0.8, '잔주름': 0.75, '피부결': 0.8 },
  },
  {
    id: 'T010',
    nameKo: '스킨보톡스',
    nameEn: 'Skin Botox',
    category: 'injectable',
    description: '미세 보톡스를 피부 전체에 주입하여 모공과 피지를 개선합니다.',
    indications: ['모공', '피지', '피부결', '작은주름'],
    contraindications: ['임신', '수유 중', '근무력증', '보톡스 알레르기'],
    typicalSessions: { min: 1, max: 1 },
    intervalDays: { min: 60, max: 90 },
    downtime: '없음',
    priceRange: { min: 200000, max: 400000 },
    effectiveness: { '모공': 0.85, '피지': 0.9, '피부결': 0.75 },
  },
  {
    id: 'T011',
    nameKo: '물광주사',
    nameEn: 'Hydra Boost',
    category: 'injectable',
    description: '히알루론산 기반의 수분 공급 주사로, 피부에 광채와 탄력을 부여합니다.',
    indications: ['수분부족', '광채', '잔주름', '피부결'],
    contraindications: ['히알루론산 알레르기', '임신', '피부 감염'],
    typicalSessions: { min: 3, max: 5 },
    intervalDays: { min: 14, max: 21 },
    downtime: '1-2일',
    priceRange: { min: 150000, max: 300000 },
    effectiveness: { '수분': 0.95, '광채': 0.85, '잔주름': 0.7, '피부결': 0.8 },
  },
  {
    id: 'T012',
    nameKo: '엑셀브이',
    nameEn: 'Excel V',
    category: 'laser',
    description: '혈관 및 색소 병변 치료에 특화된 레이저 시술입니다.',
    indications: ['홍조', '혈관확장', '색소침착', '기미', '주근깨'],
    contraindications: ['광과민성', '피부 감염', '항응고제 복용'],
    typicalSessions: { min: 3, max: 6 },
    intervalDays: { min: 21, max: 30 },
    downtime: '1-3일',
    priceRange: { min: 200000, max: 400000 },
    effectiveness: { '홍조': 0.9, '혈관확장': 0.88, '색소침착': 0.75 },
  },
  {
    id: 'T013',
    nameKo: '써마지',
    nameEn: 'Thermage',
    category: 'device',
    description: 'RF를 이용한 피부 타이트닝 시술로, 콜라겐 리모델링을 촉진합니다.',
    indications: ['피부처짐', '탄력개선', '주름', '윤곽개선'],
    contraindications: ['심장박동기', '임신', '금속 임플란트'],
    typicalSessions: { min: 1, max: 2 },
    intervalDays: { min: 180, max: 365 },
    downtime: '없음 ~ 1일',
    priceRange: { min: 1000000, max: 2500000 },
    effectiveness: { '처짐': 0.85, '탄력': 0.88, '주름': 0.75 },
  },
  {
    id: 'T014',
    nameKo: '스컬트라',
    nameEn: 'Sculptra',
    category: 'injectable',
    description: 'PLLA 성분의 콜라겐 자극 주사로, 자연스러운 볼륨 개선 효과가 있습니다.',
    indications: ['볼륨부족', '처짐', '탄력저하', '주름'],
    contraindications: ['켈로이드 체질', '임신', '자가면역질환'],
    typicalSessions: { min: 2, max: 4 },
    intervalDays: { min: 30, max: 60 },
    downtime: '1-3일 (붓기)',
    priceRange: { min: 500000, max: 1000000 },
    effectiveness: { '볼륨': 0.9, '처짐': 0.8, '탄력': 0.85 },
  },
  {
    id: 'T015',
    nameKo: '아쿠아필',
    nameEn: 'Aqua Peel',
    category: 'device',
    description: '물과 피부 친화적 용액을 이용한 피부 딥클렌징 및 보습 관리입니다.',
    indications: ['모공', '피지', '블랙헤드', '피부결', '수분'],
    contraindications: ['피부 감염', '급성 염증'],
    typicalSessions: { min: 1, max: 1 },
    intervalDays: { min: 14, max: 30 },
    downtime: '없음',
    priceRange: { min: 80000, max: 150000 },
    effectiveness: { '모공': 0.75, '피지': 0.8, '블랙헤드': 0.85, '피부결': 0.7 },
  },
  {
    id: 'T016',
    nameKo: '더모톡신',
    nameEn: 'Dermotoxin',
    category: 'injectable',
    description: '미세 보톡스와 영양 성분을 결합한 복합 피부 개선 주사입니다.',
    indications: ['모공', '피지', '피부결', '탄력', '주름'],
    contraindications: ['임신', '수유 중', '보톡스 알레르기'],
    typicalSessions: { min: 3, max: 5 },
    intervalDays: { min: 14, max: 21 },
    downtime: '없음 ~ 1일',
    priceRange: { min: 250000, max: 450000 },
    effectiveness: { '모공': 0.85, '피지': 0.88, '피부결': 0.8, '탄력': 0.75 },
  },
  {
    id: 'T017',
    nameKo: 'CO2 레이저',
    nameEn: 'CO2 Laser',
    category: 'laser',
    description: '이산화탄소 레이저를 이용한 점, 사마귀, 피부 병변 제거 시술입니다.',
    indications: ['점', '사마귀', '검버섯', '피부종양'],
    contraindications: ['켈로이드 체질', '광과민성', '피부 감염'],
    typicalSessions: { min: 1, max: 3 },
    intervalDays: { min: 30, max: 60 },
    downtime: '7-14일',
    priceRange: { min: 50000, max: 300000 },
    effectiveness: { '점': 0.95, '사마귀': 0.9, '검버섯': 0.88 },
  },
  {
    id: 'T018',
    nameKo: '실리프팅',
    nameEn: 'Thread Lift',
    category: 'injectable',
    description: '녹는 실을 이용한 피부 리프팅 시술로, 즉각적인 효과를 볼 수 있습니다.',
    indications: ['처짐', '리프팅', '턱선', '팔자주름', '탄력'],
    contraindications: ['켈로이드 체질', '임신', '혈액 응고 장애'],
    typicalSessions: { min: 1, max: 1 },
    intervalDays: { min: 365, max: 730 },
    downtime: '3-7일',
    priceRange: { min: 500000, max: 2000000 },
    effectiveness: { '처짐': 0.85, '리프팅': 0.88, '턱선': 0.8, '탄력': 0.75 },
  },
  {
    id: 'T019',
    nameKo: '트라넥삼산 이온토',
    nameEn: 'Tranexamic Acid Ionto',
    category: 'topical',
    description: '트라넥삼산을 이온토포레시스로 침투시켜 기미를 개선합니다.',
    indications: ['기미', '색소침착', '피부톤'],
    contraindications: ['트라넥삼산 알레르기', '심장박동기'],
    typicalSessions: { min: 10, max: 20 },
    intervalDays: { min: 7, max: 14 },
    downtime: '없음',
    priceRange: { min: 50000, max: 100000 },
    effectiveness: { '기미': 0.7, '색소침착': 0.65, '피부톤': 0.6 },
  },
  {
    id: 'T020',
    nameKo: '복합시술',
    nameEn: 'Combination Treatment',
    category: 'combination',
    description: '환자의 상태에 맞춰 여러 시술을 조합하여 최적의 결과를 도출합니다.',
    indications: ['복합 피부문제', '다중 증상', '종합 개선'],
    contraindications: ['개별 시술 금기사항 참조'],
    typicalSessions: { min: 3, max: 10 },
    intervalDays: { min: 14, max: 30 },
    downtime: '시술 조합에 따라 다름',
    priceRange: { min: 300000, max: 1500000 },
    effectiveness: {},
  },
];

export const getTreatmentById = (id: string): Treatment | undefined => {
  return mockTreatments.find(t => t.id === id);
};

export const getTreatmentsByCategory = (category: Treatment['category']): Treatment[] => {
  return mockTreatments.filter(t => t.category === category);
};

export const getTreatmentsForConcern = (concern: string): Treatment[] => {
  return mockTreatments.filter(t =>
    t.indications.some(ind => ind.includes(concern) || concern.includes(ind))
  );
};
